<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668740139" stop="1556668740142" version="1.4.0">
  <name>Magento\Email\Test\Unit\Model\Template\SenderResolverTest</name>
  <test-cases>
    <test-case start="1556668740139" stop="1556668740140" status="passed">
      <name>testResolve</name>
    </test-case>
    <test-case start="1556668740141" stop="1556668740141" status="passed">
      <name>testResolveThrowException with data set #0</name>
    </test-case>
    <test-case start="1556668740142" stop="1556668740142" status="passed">
      <name>testResolveThrowException with data set #1</name>
    </test-case>
  </test-cases>
</alr:test-suite>
