<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668845571" stop="1556668845574" version="1.4.0">
  <name>Magento\Framework\App\Test\Unit\ScopeResolverPoolTest</name>
  <test-cases>
    <test-case start="1556668845571" stop="1556668845572" status="passed">
      <name>testGet</name>
    </test-case>
    <test-case start="1556668845572" stop="1556668845573" status="passed">
      <name>testGetException with data set #0</name>
    </test-case>
    <test-case start="1556668845573" stop="1556668845574" status="passed">
      <name>testGetException with data set #1</name>
    </test-case>
    <test-case start="1556668845574" stop="1556668845574" status="passed">
      <name>testGetExceptionDataProvider</name>
    </test-case>
  </test-cases>
</alr:test-suite>
