<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1556668832609" stop="1556668832612" version="1.4.0">
  <name>Magento\Webapi\Test\Unit\ExceptionTest</name>
  <test-cases>
    <test-case start="1556668832609" stop="1556668832610" status="passed">
      <name>testConstruct</name>
    </test-case>
    <test-case start="1556668832610" stop="1556668832610" status="passed">
      <name>testConstructInvalidHttpCode with data set #0</name>
    </test-case>
    <test-case start="1556668832611" stop="1556668832611" status="passed">
      <name>testConstructInvalidHttpCode with data set #1</name>
    </test-case>
    <test-case start="1556668832611" stop="1556668832612" status="passed">
      <name>testGetOriginatorSender</name>
    </test-case>
    <test-case start="1556668832612" stop="1556668832612" status="passed">
      <name>testGetOriginatorReceiver</name>
    </test-case>
  </test-cases>
</alr:test-suite>
